# Site settings
title: HLP Lab
email: jaegerlab@bcs.rochester.edu
description: >
  Florian Jaeger's Human Language Processing (HLP) Lab at The University of Rochester
#baseurl: "/2015refresh" # the subpath of your site, e.g. /blog/
baseurl: ""
url: "https://www.hlplab.com" # the base hostname & protocol for your site
twitter:
  username: _hlplab_
github:
  username: hlplab
bitbucket:
  username: hlplab
wordpress:
  username: hlplab
youtube_id: UCfAMdAEbXx1vr5uZFnRfcdw
google_api_key: AIzaSyCKbJAHLypyA2q1AwXOaJh51PMyx_zO4wY
logo: /pics/UR.v2.svg
google_site_verification: UA-6365921-1

# Build settings
#markdown: redcarpet

# Generate pages even if date is in the future
future: true

kramdown:
  input: GFM

#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "underline", "space_after_headers", "with_toc_data", "fenced_code_blocks", "footnotes"]

exclude:
  - deploywww.sh
  - Gemfile
  - deps.txt
  - tmp/

plugins:
  - 'jekyll/scholar'
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-feed  

collections:
  newsblurbs:
      output: true
      permalink: /news/:year/:month/:day/:slug.html
  invited_talks:
      output: true
      permalink: /talks/:year/:month/:day/:slug.html

feed:
  path: "posts.xml"
  collections:
    newsblurbs:
        path: "news.xml"
    invited_talks:
        path: "talks.xml"

scholar:
  style: elsevier-harvard
  sort_by: author
  # bibliography: hlplab.bib
  bibliography_template: bib
  bibtex_filters:
    - latex
    #- urllink

sass:
    style: :compressed


jekyll-minifier:
  exclude: 'atom.xml'
  compress_css: false                # Default: true
  compress_javascript: false         # Default: true

#  You should set your JEKYLL_ENV=development on your development machine and JEKYLL_ENV=production when building to push.
#  Being in production mode causes octopress-minify-html to minify and jekyll-assets to add digests to filenames

# Uncomment this to not minify even in production
# minify_html: false

# Temporarily commenting this out because the sha hashes it generates are wrong
assets:
  # If you compress the assets the integrity hash comes out wrong
  # https://github.com/jekyll/jekyll-assets/issues/328
  compress:
    css: false
    js: false
  digest: false
  features:
    integrity: true
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"

defaults:
  - scope:
      path: ""
      type: "newsblurbs"
    values:
      layout: newsblurb

  - scope:
      path: ""
      type: "invited_talks"
    values:
      layout: talk_detail
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      permalink: /news/:year/:month/:day/:title.html
#
