# Site settings
title: HLP Lab
email: jaegerlab@bcs.rochester.edu
description: >
  Florian Jaeger's Human Language Processing (HLP) Lab at The University of Rochester
#baseurl: "/2015refresh" # the subpath of your site, e.g. /blog/
baseurl: ""
url: "https://www.hlp.rochester.edu" # the base hostname & protocol for your site
twitter:
  username: _hlplab_
github:
  username: hlplab
bitbucket:
  username: hlplab
wordpress:
  username: hlplab
youtube_id: UCfAMdAEbXx1vr5uZFnRfcdw
google_api_key: AIzaSyCKbJAHLypyA2q1AwXOaJh51PMyx_zO4wY
logo: /pics/UR.v2.svg

# Build settings
#markdown: redcarpet

kramdown:
  input: GFM

#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "underline", "space_after_headers", "with_toc_data", "fenced_code_blocks", "footnotes"]

exclude: [deploywww.sh, Gemfile]

gems:
  - 'jekyll/scholar'
  - jekyll-seo-tag
  - jekyll-sitemap
  - octopress-quote-tag
  - octopress-minify-html
  - jekyll-textile-converter

scholar:
  style: elsevier-harvard
  sort_by: name
  bibliography: hlplab.bib
  bibliography_template: bib
  bibtex_filters:
    - latex
    #- urllink

sass:
    style: :compressed

#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      permalink: /news/:year/:month/:day/:title.html
#
